global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'clinic-crm'
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['clinic-crm-5nec.onrender.com']
